#!/bin/bash
#
# Vanus
#
echo -n "Sisesta oma vanus: "
read vanus
if test $vanus -gt 0 -a $vanus -lt 11
then
echo "oled laps"
elif test $vanus -ge 11 -a $vanus -lt 18
then
echo "olen nooruk"
elif test $vanus -ge 18 -a $vanus -lt 63
then
echo "oled t2iskasvanu"
elif test $vanus -ge 65
then
echo "Oled Senjoor"
else
echo "vigane sisend"
fi
#
# l6pp
