#!/bin/bash
#
# Ylesanne 2
#
echo -n "Sisesta suvaline t2isarv: "
read arv
summa=0
while [ $arv -ne 0 ]
do
jaak=$(($arv % 10))
summa=$(($summa + $jaak))
arv=$(($arv / 10))
done
echo "$summa"
#
# Skripti l6pp
