#!/bin/bash
#
# Ylesanne 3
#
echo -n "Sisesta kuu: "
read kuu
case $kuu in
"1") echo "See on jaanuar";;
"2") echo "See on veebruar";;
"3") echo "See on marts";;
"4") echo "See on aprill";;
"5") echo "See on mai";;
"6") echo "See on juuni";;
"7") echo "See on juuli";;
"8") echo "See on august";;
"9") echo "See on september";;
"10") echo "See on oktoober";;
"11") echo "See on november";;
"12") echo "See on detsember";;
*) echo "See on vale number, meil on ainult 12 kuud";;
esac
#
# Skripti l6pp
