#!/bin/bash
#
# Ylesanne1
#
echo -n "Sisesta oma ees- ja perenimi: " #V2ljastab teksti
read eesnimi perenimi #loeb v2lja eesnime ja perekonnanime
echo "Sinu eesnimi on $eesnimi ja perenimi on $perenimi" #V2ljastab andmed
#
# Skripti l6pp
